#untilsuccessful
untilSuccess:
  retries: "2"
  timeInterval: "3000"

#Common properties
common:
  errors:
    error-code-400: "BAD_REQUEST"
    error-code-404: "NOT_FOUND"
    error-code-405: "METHOD_NOT_ALLOWED"
    error-code-406: "NOT_ACCEPTABLE"
    error-code-415: "UNSUPPORTED_MEDIA_TYPE"
    error-code-500: "INTERNAL_SERVER_ERROR"
    error-code-501: "NOT_IMPLEMENTED"    
    
#Source and Target Names
source:
  name: "PDI-Enterprise"  
target:
  name: "SFDC"  
  
#Logger category
milestone:
  category: "LOG"
logger:
  category: "LOG"    

#timezone
timeZone: "US/Eastern"   